[build]
  functions = "netlify/functions"
  command = "echo 'No build needed'"

# Disable secrets scanning for these paths (if needed)
[secrets]
  scan_omit_paths = ["netlify/functions/*"]
  scan_enabled = false
